import React from 'react';
import { ArrowRight, Clock, FlaskConical } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Blog() {
    const navigate = useNavigate();

    const labNotes = [
        {
            id: "the-seed-strategy",
            title: "Seed Strategy: How to Bring Market-Breaking Analyses?",
            date: "March 14, 2026",
            excerpt: "To make your analyses 'gold', you must stop looking at features and start looking at output. Meet the Aether Audit method.",
            readTime: "4 min read"
        },
        {
            id: "claude-3-5-sonnet-coding-test",
            title: "Claude 3.5 Sonnet Under the Microscope: Is the Coding Revolution Really Here?",
            date: "February 12, 2026",
            excerpt: "We put Anthropic's new model through dozens of coding tests, from extending React components to creating cloud architectures. The findings are surprising.",
            readTime: "6 min read"
        },
        {
            id: "rise-of-autonomous-agents",
            title: "The Rise of Autonomous AI Agents: Why 'Agentic' Changes the Game",
            date: "February 05, 2026",
            excerpt: "A review of the shift from simple Chatbots to agents capable of planning complex strategies and making multi-step decisions in production.",
            readTime: "8 min read"
        },
        {
            id: "ai-writing-tools-turing-test",
            title: "AI Writing Tools vs. Humans: Results of the Aether Turing Test",
            date: "January 28, 2026",
            excerpt: "Can CEOs distinguish between a strategy document written by an executive and one generated by ChatGPT after fine-tuning? Full data from our latest lab study.",
            readTime: "5 min read"
        }
    ];

    const handlePostClick = (id) => {
        navigate(`/blog/${id}`);
    };

    return (
        <div className="min-h-screen w-full flex flex-col items-center bg-[#0a0a0c] pt-24 pb-24 ltr animate-in fade-in duration-700" dir="ltr">
            <main className="w-full max-w-3xl px-6">

                {/* Header */}
                <div className="mb-16 border-b border-white/10 pb-12 relative">
                    <button onClick={() => navigate(-1)} className="absolute top-0 left-0 text-white/50 hover:text-white transition-colors flex items-center gap-2 text-sm font-bold bg-white/5 backdrop-blur-md px-3 py-1.5 rounded-md border border-white/10 mb-8 -translate-y-full">
                        <ArrowRight className="w-4 h-4 rotate-180" /> Back
                    </button>

                    <div className="inline-flex items-center gap-2 px-3 py-1 mb-6 rounded-md bg-white/5 backdrop-blur-md border border-white/10 text-white/50 text-xs font-bold tracking-widest font-mono uppercase mt-6">
                        <FlaskConical className="w-3 h-3" /> Aether Lab
                    </div>
                    <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight mb-4">
                        Lab Notes
                    </h1>
                    <p className="text-xl text-white/50 font-medium max-w-2xl">
                        Thoughts, research, and field tests we conduct on the latest AI tools. Sponsored-free, spin-free. What you read is what we found.
                    </p>
                </div>

                {/* Feed */}
                <div className="flex flex-col gap-12">
                    {labNotes.map((note) => (
                        <article key={note.id} className="group cursor-pointer" onClick={() => handlePostClick(note.id)}>
                            <div className="flex items-center gap-4 mb-3 text-sm text-white/30 font-mono tracking-wider uppercase">
                                <time>{note.date}</time>
                                <span className="w-1 h-1 rounded-full bg-white/20"></span>
                                <span className="flex items-center gap-1.5"><Clock className="w-3 h-3" /> {note.readTime}</span>
                            </div>
                            <h2 className="text-2xl font-bold text-white mb-3 group-hover:text-cyan-400 transition-colors underline-offset-4 group-hover:underline">
                                {note.title}
                            </h2>
                            <p className="text-white/50 leading-relaxed font-medium mb-4">
                                {note.excerpt}
                            </p>
                            <span className="text-cyan-500 text-sm font-bold flex items-center gap-1 group-hover:text-cyan-400 transition-colors">
                                Read full research <ArrowRight className="w-3 h-3 transition-transform group-hover:translate-x-1" />
                            </span>
                        </article>
                    ))}
                </div>

            </main>
        </div>
    );
}
